# Generated by Django 4.2.4 on 2023-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_category_comments_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
